# Generated by Django 5.2.5 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_loginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginotp",
            name="otp_token_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
