# Generated by Django 5.2.5 on 2026-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_loginotp_otp_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
