# Generated by Django 5.2.5 on 2026-08-29 13:42

from django.db import migrations, models


def normalize_existing_phones(apps, schema_editor):
    User=apps.get_model("core","User");seen=set()
    for user in User.objects.order_by("id"):
        digits="".join(ch for ch in (user.phone or "") if ch.isdigit())
        value=("+"+digits) if (user.phone or "").startswith("+") else ("+91"+digits if len(digits)==10 else "+"+digits if digits else None)
        if value in seen:value=None
        if value:seen.add(value)
        User.objects.filter(pk=user.pk).update(phone_e164=value)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_e164',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_existing_phones,migrations.RunPython.noop),
    ]
