# Generated by Django 5.2.5 on 2026-08-29 13:57

from django.db import migrations, models


def select_one_company_role(apps,schema_editor):
    UserRole=apps.get_model("core","UserRole");AuditLog=apps.get_model("core","AuditLog")
    pairs=UserRole.objects.values_list("tenant_id","user_id").distinct()
    for tenant_id,user_id in pairs:
        rows=list(UserRole.objects.filter(tenant_id=tenant_id,user_id=user_id))
        rows.sort(key=lambda row:(row.branch_id is None,row.created_at,row.pk),reverse=True)
        keep=rows[0];UserRole.objects.filter(pk=keep.pk).update(is_active=True,branch_id=None)
        if len(rows)>1:
            disabled=[row.pk for row in rows[1:]];UserRole.objects.filter(pk__in=disabled).update(is_active=False)
            AuditLog.objects.create(tenant_id=tenant_id,actor_id=keep.assigned_by_id,action="rbac.roles_consolidated_per_company",resource_type="User",resource_id=str(user_id),metadata={"kept_assignment":keep.pk,"inactive_historical_assignments":disabled,"reason":"One active role per person per company"})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_e164_user_phone_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(select_one_company_role,migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'user'), name='one_active_role_per_company_user'),
        ),
    ]
